### ISSUE TITLE
Move release CI to GitHub

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#611]
## Description

Currently, the release is built in Camunda's Jenkins. We should migrate to GitHub actions. 

We can get inspired by [Zeebe's release workflow](https://github.com/camunda/zeebe/blob/main/.github/workflows/release.yml).
```[tasklist]
### Tasks
- [ ] Polish the GitHub workflow
- [x] Ensure that the 3rd party license list is generated
- [x] Remove the Jenkins pipeline
```

**Comment by saig0** [comment]
Not yet done. Let's keep the issue open until a first release is build.

**Comment by saig0** [comment]
I requested access to the Vault:https://github.com/camunda/infra-core/pull/5981.

**Comment by saig0** [comment]
The workflow was [successful](https://github.com/camunda/feel-scala/actions/runs/5666095205) and built the `1.17.0-alpha1` release. :tada:
